#!/bin/bash
#
# Wrap the built `swift build` binary into a real CLIP.app bundle: app icon,
# version stamp, the self-update feed URL, an ad-hoc code signature, and
# (optionally) a distributable .zip. (Typography is SF Mono — a system face —
# so there are no font files to bundle.)
#
# On macOS 26 (Tahoe) the system masks the icon to the squircle and applies
# the Liquid Glass material automatically to the bundled .icns.
#
# Usage:
#   swift build -c release
#   Scripts/make-app.sh                          # → ./CLIP.app  (dev: no feed, no update)
#   MARKETING=1.2 BUILD=14 Scripts/make-app.sh    # stamp version (BUILD must increase per release)
#   FEED_URL="https://raw.githubusercontent.com/<user>/clip/main/appcast/latest.json" \
#     MARKETING=1.2 BUILD=14 ZIP=1 DMG=1 Scripts/make-app.sh /Applications
#
# Env:
#   CONFIG    build config dir under .build (default: release)
#   MARKETING marketing version string  (default 1.0)
#   BUILD     integer build number       (default 1) — the updater compares this
#   FEED_URL  update manifest URL; omit/empty ⇒ this build never self-updates (dev)
#   ZIP=1     also emit CLIP.zip next to the .app — used by the silent self-updater
#             (it unzips via `ditto -x -k`); the manifest URL points here.
#   DMG=1     also emit CLIP.dmg (drag-to-Applications) — the friendly artifact
#             humans download from the website. Updater never touches the DMG.
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG="${CONFIG:-release}"
BIN="$ROOT/.build/$CONFIG/CLIP"
ICON="$ROOT/AppIcon/AppIcon.icns"
MARKETING="${MARKETING:-1.0}"
BUILD="${BUILD:-1}"
FEED_URL="${FEED_URL:-}"

DEST_DIR="${1:-$ROOT}"
APP="$DEST_DIR/CLIP.app"
PB=/usr/libexec/PlistBuddy

[ -f "$BIN" ]  || { echo "✗ no binary at $BIN — run: swift build -c $CONFIG"; exit 1; }
[ -f "$ICON" ] || { echo "✗ no icon at $ICON"; exit 1; }

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BIN"  "$APP/Contents/MacOS/CLIP"
cp "$ICON" "$APP/Contents/Resources/AppIcon.icns"   # classic fallback

# --- Native app icon (Icon Composer .icon → Liquid Glass on macOS 26) ---
# If AppIcon/AppIcon.icon exists and actool is available, compile it natively:
# actool emits Assets.car (the Liquid Glass icon the system renders on Tahoe) +
# a fallback AppIcon.icns + CFBundleIconName. Falls back to the classic .icns
# above when actool isn't present.
ICON_DOT="$ROOT/AppIcon/AppIcon.icon"
ACTOOL="$(/usr/bin/xcrun -f actool 2>/dev/null || true)"
if [ -z "$ACTOOL" ]; then
  XC_APP="$(ls -d /Applications/Xcode*.app 2>/dev/null | head -1)"
  [ -n "$XC_APP" ] && ACTOOL="$XC_APP/Contents/Developer/usr/bin/actool"
fi
ICON_NATIVE=0
if [ -d "$ICON_DOT" ] && [ -n "$ACTOOL" ] && [ -x "$ACTOOL" ]; then
  ICON_OUT="$(mktemp -d)"
  if "$ACTOOL" "$ICON_DOT" --compile "$ICON_OUT" --platform macosx \
        --minimum-deployment-target 26.0 --app-icon AppIcon \
        --output-partial-info-plist "$ICON_OUT/icon.plist" >/dev/null 2>&1 \
     && [ -f "$ICON_OUT/AppIcon.icns" ]; then
    # Use ONLY the flattened icns — Tahoe still auto-masks it to a squircle and
    # applies the glass material, so it still looks native. We deliberately DON'T
    # ship Assets.car: its Liquid Glass render IGNORES the Icon Composer layer
    # `scale` (always fills the tile), so the flattened icns — which honours the
    # scale — is the only way to control the on-screen size.
    cp "$ICON_OUT/AppIcon.icns" "$APP/Contents/Resources/AppIcon.icns"
  fi
  rm -rf "$ICON_OUT"
fi

# SPM resource bundle (`Bundle.module`) — generated by `swift build` next to the
# binary. Without it the generated `resource_bundle_accessor` asserts at launch
# (NSBundle.module not found → ClipApp.applyIcon crash). DIFFERENT toolchains
# generate accessors that probe DIFFERENT locations — some `Bundle.main.resourceURL`
# (= Contents/Resources), some the executable dir (Contents/MacOS), and some
# `Bundle.main.bundleURL` (the .app ROOT). The release v1.0.393 crashed on clean
# machines because its (CI-toolchain) accessor looked at the .app root while we
# only copied to Contents/, AND that toolchain emitted a FLAT bundle with no
# Info.plist (so `Bundle(url:)` returned nil even where it did look). Be robust:
# place a copy at ALL THREE candidate locations and guarantee each has an
# Info.plist so `Bundle(url:)` always initializes.
if [ -d "$ROOT/.build/$CONFIG/CLIP_CLIP.bundle" ]; then
  BUNDLE_SRC="$ROOT/.build/$CONFIG/CLIP_CLIP.bundle"
  BUNDLE_PLIST="$(mktemp)"
  cat > "$BUNDLE_PLIST" <<'BNDL'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleIdentifier</key><string>clip.CLIP.resources</string>
  <key>CFBundleName</key><string>CLIP_CLIP</string>
  <key>CFBundlePackageType</key><string>BNDL</string>
</dict>
</plist>
BNDL
  for BUNDLE_DST in "$APP/Contents/Resources/CLIP_CLIP.bundle" \
                    "$APP/Contents/MacOS/CLIP_CLIP.bundle" \
                    "$APP/CLIP_CLIP.bundle"; do
    rm -rf "$BUNDLE_DST"
    cp -R "$BUNDLE_SRC" "$BUNDLE_DST"
    # If SwiftPM emitted a flat bundle with no Info.plist (CI toolchain), add a
    # minimal one at the root so the bundle is a valid, loadable bundle.
    if [ ! -f "$BUNDLE_DST/Contents/Info.plist" ] && [ ! -f "$BUNDLE_DST/Info.plist" ]; then
      cp "$BUNDLE_PLIST" "$BUNDLE_DST/Info.plist"
    fi
  done
  rm -f "$BUNDLE_PLIST"
fi

cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>CLIP</string>
  <key>CFBundleDisplayName</key><string>CLIP</string>
  <key>CFBundleExecutable</key><string>CLIP</string>
  <key>CFBundleIdentifier</key><string>com.clip.app</string>
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>LSMinimumSystemVersion</key><string>13.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>NSPrincipalClass</key><string>NSApplication</string>
  <key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLName</key><string>com.clip.app</string>
      <key>CFBundleURLSchemes</key>
      <array><string>clip</string></array>
    </dict>
  </array>
</dict>
</plist>
PLIST

# Stamp version + (optional) update feed URL.
"$PB" -c "Set :CFBundleShortVersionString $MARKETING" "$APP/Contents/Info.plist"
"$PB" -c "Set :CFBundleVersion $BUILD"                 "$APP/Contents/Info.plist"
if [ -n "$FEED_URL" ]; then
  "$PB" -c "Add :CLIPFeedURL string $FEED_URL" "$APP/Contents/Info.plist" 2>/dev/null \
    || "$PB" -c "Set :CLIPFeedURL $FEED_URL" "$APP/Contents/Info.plist"
fi

# Native icon → point LaunchServices at the compiled Assets.car icon.
if [ "${ICON_NATIVE:-0}" = "1" ]; then
  "$PB" -c "Add :CFBundleIconName string AppIcon" "$APP/Contents/Info.plist" 2>/dev/null \
    || "$PB" -c "Set :CFBundleIconName AppIcon" "$APP/Contents/Info.plist"
fi

# Ad-hoc sign: a stable signature so the app launches cleanly and survives the
# in-place self-update swap. Still "unsigned" to Gatekeeper (no Developer ID).
codesign --force --deep --sign - "$APP" >/dev/null 2>&1 || true

# Nudge LaunchServices + the icon cache so Finder/Dock pick up the new icon.
/usr/bin/touch "$APP"
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f "$APP" >/dev/null 2>&1 || true

echo "✓ built $APP  (v$MARKETING build $BUILD${FEED_URL:+, feed set})"

# ZIP — the artifact the SILENT SELF-UPDATER downloads (it unzips via ditto -x -k).
# Stable name (CLIP.zip) so the manifest's /releases/latest/download/CLIP.zip
# URL is permanent across versions. Not the human download — that's the DMG.
if [ "${ZIP:-}" = "1" ]; then
  ZIP_PATH="$DEST_DIR/CLIP.zip"
  rm -f "$ZIP_PATH"
  ( cd "$DEST_DIR" && /usr/bin/ditto -c -k --keepParent "CLIP.app" "$ZIP_PATH" )
  echo "✓ zipped $ZIP_PATH  (self-updater artifact)"
  echo "  sha256: $(shasum -a 256 "$ZIP_PATH" | awk '{print $1}')"
fi

# DMG — the friendly artifact HUMANS download from the website. Mounts to a
# window with CLIP.app + an Applications shortcut so visitors drag-to-install.
# The updater never touches this (it uses the ZIP above).
if [ "${DMG:-}" = "1" ]; then
  DMG_PATH="$DEST_DIR/CLIP.dmg"
  rm -f "$DMG_PATH"
  STAGE="$(mktemp -d)/CLIP"
  mkdir -p "$STAGE"
  /usr/bin/ditto "$APP" "$STAGE/CLIP.app"     # copy the signed bundle in
  ln -s /Applications "$STAGE/Applications"    # drag-target shortcut
  /usr/bin/hdiutil create \
    -volname "CLIP" \
    -srcfolder "$STAGE" \
    -fs HFS+ -format UDZO -ov \
    "$DMG_PATH" >/dev/null
  rm -rf "$(dirname "$STAGE")"
  echo "✓ made $DMG_PATH  (human download — drag to Applications)"
  echo "  sha256: $(shasum -a 256 "$DMG_PATH" | awk '{print $1}')"
fi
